name: Dependabot auto-merge
on:
    pull_request:
        types: [opened, reopened]
    workflow_call:

jobs:
    dependabot:
        if: ${{ github.actor == 'ChinaGodMan' }}
        runs-on: ubuntu-latest
        env:
          GIT_AUTHOR_NAME: ${{ github.event.commits[0].author.name }}
          GIT_AUTHOR_EMAIL: ${{ github.event.commits[0].author.email }}
          GIT_COMMITTER_NAME: qinwuyuan-sync-bot
          GIT_COMMITTER_EMAIL: chinagodman1@gmail.com
        
        steps:
            - name: 检出代码
              uses: actions/checkout@v4
            
            - name: 配置 GPG 签名
              run: |
                gpg --batch --import <(echo "${{ secrets.GPG_PRIVATE_KEY }}")
                git config --global commit.gpgsign true
                git config --global user.signingkey "${{ secrets.GPG_PRIVATE_ID }}"
            
            - name: 获取分支名称
              id: get_branch_name
              run: echo "branch_name=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV
            
            - name: 签名合并并推送
              run: |
                git checkoutmain
                git merge ${{ env.branch_name }}
                git push origin main
