name: 归零大法-清空仓库大小
on:
  workflow_dispatch:  
  schedule:           
    - cron: '0 0 25 * *'  
  

jobs:
  check-size-and-reset:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 检查仓库大小
        id: check_size
        run: |
          repo_size=$(du -sm . | cut -f1)  # 获取仓库大小（以MB为单位）
          echo "Repository size: ${repo_size} MB"
          echo "::set-output name=size::${repo_size}"  # 设置为输出变量

      - name: 创建孤儿分之并推送到仓库
        if: steps.check_size.outputs.size > 800  # 当仓库大小大于10MB时执行
        run: |
          git config --local user.email "chinagodman1@gmail.com"
          git config --local user.name "qinwuyuan-sync-bot"
          git checkout --orphan temp-branch  # 创建孤儿分支
          git commit --allow-empty -m ":trollface: 仓库过大，自动归零"
          git push origin temp-branch:main --force
