name: Auto Assign PR to Repository Owner

on:
  pull_request:
    types: [opened]

jobs:
  assign-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Assign PR to repository owner
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.BOT_TOKEN }} 
          script: |
            const prOwner = context.repo.owner;
            const pullRequest = context.payload.pull_request;
            const pull_number = pullRequest.number;
            const prAuthor = pullRequest.user.login; 

            // 添加受理人
            await github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pull_number, 
              assignees: [prOwner]  
            });

            // 请求审阅
            if (prOwner !== prAuthor) {
              await github.rest.pulls.requestReviewers({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pull_number,
                reviewers: [prOwner] 
              });
            } else {
              console.log(`跳过请求审阅，因为 PR 的作者是 ${prAuthor}`);
            }
