name: Auto Assign PR to Repository Owner

on:
  pull_request:X
    types: [opened]

jobs:
  assign-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Assign PR to repository owner
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.BOT_TOKEN }}  
          script: |
            const prOwner = context.repo.owner;
            await github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              reviewers: [prOwner]  
            });
