name: Auto Assign PR to Repository Owner

on:
  pull_request:
    types: [opened]

jobs:
  assign-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Assign PR to repository owner
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} 
          script: |
            const prOwner = context.repo.owner;
            const pull_number = context.payload.pull_request.number;
            
            // 添加受理人（assignees）
            await github.rest.pulls.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pull_number,
              assignees: [prOwner] 
            });

            // 请求审阅
            await github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pull_number,
              reviewers: [prOwner] 
            });
