name: Greasyf

on:
  schedule:
    - cron: '0 */2 * * *'  # 每两个小时更新一次
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.MY_GITHUB_TOKEN }}  # 使用你创建的 Token

    - name: Download README.md from remote URL
      run: |
        curl -L -o docs/readme.md https://github.com/ChinaGodMan/UserScripts/raw/main/docs/README.md

    - name: Check README.md content
      run: |
        cat docs/readme.md  # 检查文件是否包含内容，确保下载成功

    - name: Commit and push if README.md changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/readme.md
        git diff --quiet && git diff --staged --quiet || git commit -m "Update docs/readme.md from remote"
        git push origin ${{ env.GITHUB_REF_NAME }}
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}  # 传递 Token 到 Git 环境变量中
