name: Auto Assign Issue to Repository Owner

on:
  issues:
    types: [opened]

jobs:
  assign-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Assign issue to repository owner
        uses: actions/github-script@v6
        with:
          script: |
            const issueOwner = context.repo.owner;
            github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              assignees: [issueOwner]
            });
